# openapi.yaml
openapi: "3.0.0"
info:
  title: "My API"
  version: "1.0.0"
paths:
  /api/query:
    post:
      summary: "Query the database"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                sql_query:
                  type: string
      responses:
        "200":
          description: "Successful response"
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
